      - name: Deploy to VPS via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
          VPS_USER: ${{ secrets.VPS_USER }}  
          VPS_HOST: ${{ secrets.VPS_HOST }}  
        run: |
          # Ensure .ssh directory exists
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Save SSH private key and set correct permissions
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem  

          # Add the VPS to known hosts to prevent SSH host verification prompt
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Set correct permissions for known_hosts

          # Connect to the VPS and execute deployment commands
          ssh -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST <<EOF
          cd /hillborn  # Adjust to your project directory
          git pull origin main  
          npm install  
          npm run build  
          pm2 restart nextjs-app  
          sudo systemctl restart nginx  
          EOF
